[build]
  command = "chmod +x ./build-netlify.sh && ./build-netlify.sh"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.4"
  NPM_FLAGS = "--legacy-peer-deps --force"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200